// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "AnchorBuildWeek",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Anchor Build Week",
            targets: ["AppModule"],
            bundleIdentifier: "com.Ryunosuke.AnchorBuildWeek",
            teamIdentifier: "V7F5K95K4G",
            displayVersion: "1.1",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait
            ],
            additionalInfoPlistContentFilePath: "InfoPlist_Additions.plist"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources"),
                .process("PrivacyInfo.xcprivacy")
            ]
        )
    ]
)