import Foundation

/// Defines the payload structure for the Offline Shield QR.
/// Designed to be readable both as a raw JSON dump (fallback) and via formatted helpers.
struct ShieldQRPayload: Codable, Sendable {
  // Versioning for future compatibility
  var v: Int = 1

  // Core Message
  var situation: String
  var doText: String
  var dontText: String
  var safetyText: String?

  // Optional Metadata
  var supporter: SupporterContact?

  struct SupporterContact: Codable, Sendable {
    var name: String?
    var phone: String?
  }

  // MARK: - Export Formats

  /// Returns a clean, human-readable plain text string (Full).
  /// This is the PRIMARY format for QR codes to ensure cross-platform compatibility
  /// and avoid system misinterpretation (e.g. "Add Contact" prompts).
  /// - Parameter includePhone: If true, includes the support contact's phone number. Defaults to false for privacy/safety.
  func asPlainText(includePhone: Bool = false) -> String {
    var text = """
      ANCHOR_SHIELD_V1
      READ HERE (NO INTERNET)

      SITUATION:
      \(situation)

      WHAT HELPS:
      \(doText)

      PLEASE AVOID:
      \(dontText)
      """

    if let safety = safetyText, !safety.isEmpty {
      text += "\n\nSAFETY:\n\(safety)"
    }

    if let supporter = supporter, let name = supporter.name, !name.isEmpty {
      // Default to Name only. Phone is excluded by default to preventing "Contact" detection.
      text += "\n\nSUPPORT CONTACT:\n\(name)"

      if includePhone, let phone = supporter.phone, !phone.isEmpty {
        text += " (\(phone))"
      }
    }

    // Footer
    text += "\n\n(Generated by Anchor)"

    return text
  }

  /// Returns a shortened plain text string for capacity-constrained scenarios.
  func asShortPlainText(includePhone: Bool = false) -> String {
    var text = """
      [ ANCHOR SUPPORT CARD ]

      SITUATION:
      \(situation)
      """

    if let supporter = supporter, let name = supporter.name, !name.isEmpty {
      text += "\n\nSUPPORT CONTACT: \(name)"
      if includePhone, let phone = supporter.phone, !phone.isEmpty {
        text += " \(phone)"
      }
    }

    return text
  }
}
